CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL CHECK (char_length(trim(username)) BETWEEN 2 AND 50),
  email VARCHAR(254) NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique_idx ON users (email);

CREATE TABLE IF NOT EXISTS todos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL CHECK (char_length(trim(title)) BETWEEN 1 AND 200),
  note VARCHAR(2000),
  reminder TIMESTAMPTZ,
  priority VARCHAR(20) NOT NULL DEFAULT 'Trung bình'
    CHECK (priority IN ('Thấp', 'Trung bình', 'Cao')),
  category VARCHAR(30) NOT NULL DEFAULT 'Khác'
    CHECK (category IN ('Công việc', 'Cá nhân', 'Mua sắm', 'Sức khỏe', 'Khác')),
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  "userId" INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS todos_user_created_at_idx ON todos ("userId", created_at DESC);
CREATE INDEX IF NOT EXISTS todos_user_completed_idx ON todos ("userId", completed);
CREATE INDEX IF NOT EXISTS todos_reminder_idx ON todos (reminder) WHERE reminder IS NOT NULL;

-- Bring legacy databases up to the same minimum guarantees without rewriting data.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'todos_user_id_fkey'
  ) THEN
    ALTER TABLE todos
      ADD CONSTRAINT todos_user_id_fkey
      FOREIGN KEY ("userId") REFERENCES users(id) ON DELETE CASCADE NOT VALID;
  END IF;
END $$;
